# Generated by Django 5.2.9 on 2025-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.CharField(blank=True, help_text='Ex: 120 x 80 x 60 cm', max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif de la photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
