# Generated by Django 5.2.9 on 2025-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('maison', 'Maison'), ('mode', 'Mode'), ('jouet', 'Jouet'), ('bricole', 'Bricole'), ('culture', 'Culture'), ('sport', 'Sport'), ('meubles', 'Meubles')], default='maison', max_length=20),
        ),
    ]
