# Generated by Django 5.2.9 on 2025-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('maison', 'Maison'), ('mode', 'Mode'), ('jouet', 'Jouet'), ('bricolage', 'Bricolage'), ('culture', 'Culture'), ('sport', 'Sport'), ('meubles', 'Meubles')], default='maison', max_length=20),
        ),
    ]
